env: local # might be local, dev, prod
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8082"
  timeout: 4s #время на чтение запроса
  idle-timeout: 60s #время жизни соединения с клиентом
  user: "myuser"
  password: "mypass"